/*
BITRIX24
USER ACTIVITY BY YEAR AND MONTH
*/
SELECT 
	YEAR(DATE_CREATE) AS year, 
	MONTH(DATE_CREATE) AS month, 
	COUNT(ID) as sum 
FROM b_im_message 
GROUP BY YEAR(DATE_CREATE), MONTH(DATE_CREATE);
/*
USER ACTIVITY BY HOUR
*/
SELECT 
	HOUR(DATE_CREATE) as hour, 
	COUNT(ID) AS  sum 
FROM b_im_message 
GROUP BY HOUR(DATE_CREATE) 
ORDER BY sum DESC;
/*
USER ACTIVITY BY YEAR AND MONTH AND NOTIFY MODULE
*/
SELECT 
	YEAR(DATE_CREATE) AS year, 
	MONTH(DATE_CREATE) AS month, 
	NOTIFY_MODULE AS module,
	COUNT(ID) as sum 
FROM b_im_message 
GROUP BY YEAR(DATE_CREATE), MONTH(DATE_CREATE), NOTIFY_MODULE;
/*
TOTAL MESSAGE'S STATUS
*/
SELECT
	PARAM_NAME,
	COUNT(ID) as total
FROM
	b_im_message_param
GROUP BY PARAM_NAME 
/*
NEW USER REGISTRATION MONTHLY
*/
SELECT
	YEAR(DATE_REGISTER) AS year, 
	MONTH(DATE_REGISTER) AS month,
	COUNT(ID)
FROM
	b_user
GROUP BY YEAR(DATE_REGISTER), MONTH(DATE_REGISTER)
/*
COUNT DELETED MESSAGES
*/
SELECT 
	YEAR(b_im_message.DATE_CREATE) AS year,
	COUNT(b_im_message.ID) 
FROM 
	b_im_message, b_im_message_param
WHERE 
	b_im_message.ID=b_im_message_param.MESSAGE_ID
AND
	b_im_message_param.PARAM_NAME = 'IS_DELETED'
GROUP BY 
	YEAR(b_im_message.DATE_CREATE)
/*
CONNECTIONS
*/
SHOW STATUS WHERE variable_name LIKE "Threads_%" OR variable_name = "Connections"
SELECT /*+ MAX_EXECUTION_TIME(1000) */ status, count(*) FROM articles GROUP BY status ORDER BY status;
show variables like '%log%';
SHOW INDEXES FROM table_name;


/*b_bp_track count row by document*/
SELECT
	*
FROM (
	SELECT
		T2.DOCUMENT_ID EL,
		COUNT(T1.ID) total
	FROM 
		b_bp_tracking T1
	LEFT JOIN
		b_bp_workflow_instance T2
	ON T1.WORKFLOW_ID = T2.ID
	GROUP BY T1.WORKFLOW_ID
	ORDER BY T2.DOCUMENT_ID DESC
) T12
WHERE T12.total > 1000
